### ISSUE TITLE
Please document when `HashMap::insert_async` can wait

### ISSUE THREAD

**Issue by joshtriplett** [wvwwvwwv/scalable-concurrent-containers#145]
It's not entirely clear under what circumstances `HashMap::insert_async` will wait. Is it possible for `insert_async` to have to wait, if a reader currently has a reference to an item in the same bucket in which `HashMap` wants to do the insert?

Details: I'm considering a design that has a table of `OnceCell` values, which get created when kicking off a network request for a set of resources, and initialized when the request comes back. I want to make sure that tasks blocking on a `OnceCell` don't block the insertion of new `OnceCell`s.

**Comment by wvwwvwwv** [comment]
Yes, your understanding is correct. Minor, but one thing to note is that `*_async` methods don't technically block, but they *suspend/yield* if the desired resource (in this case, bucket) cannot be immediately acquired. In order to minimise false sharing, I would consider initialising HashMap with a large capacity.

Not sure if I understood the usage correctly, but I don't think it's a good design to hold a reference to an OnceCell when making network requests, since entries sharing the same bucket won't be accessible to others.

**Comment by joshtriplett** [comment]
I appreciate the update; now that I know the circumstances under which insert operations can block, I'll go with a different design.
