### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by orenbenkiki** [wvwwvwwv/scalable-concurrent-containers#29]
I'm looking for a lock-free hash table to use for memoizing objects during a parallel search. Basically I convert every (large) key to a small (4 byte) unique ID, so the IDs can refer back to the keys and to index per-key data (stored in separate vector(s)). A minor downside of this is that the key is stored twice, once inside the hash table (of course) and once in a vector indexed by the ID (to allow id-to-key operation, the reverse of the hash table's key-to-id operation).

Right now I'm using hashbrown which obviously isn't a optimal since it requires a global write lock on every insert, so parallel scalability is an issue.

When looking into switching to scc, I hit on two issues:

* Major issue: The ideal API for me would have `table.read_or_insert(key, |key| make_value(key) -> value, |key, value| use_value(key, value) -> result) -> result` - this way, if the key exists I'll get the current unique ID associated with the key (this is a memoization table after all...), and I'd only generate a new ID (using an `Atomic` operation) if the key doesn't exist. I _think_ I can't achieve this with the current API in a lock-free way?
* Minor issue: It would be nice to have a `reserve(additional)` function to go with the `capacity` function. Initializing with a given capacity is great, but at times in the algorithm I wish to explicitly reserve a larger additional capacity that I know I'll be using.

**Comment by orenbenkiki** [comment]
Hmmm, re-reading the documentation for `insert` it seems I can do this by inserting a dummpy value, matching on the results, if the key existed overwrite the newly-written dummpy value by the old one, otherwise overwrite it by a newly generated one. I'll give that a try.

**Comment by wvwwvwwv** [comment]
Thanks for your feature requests. They all totally make sense to me, and I'll address both of them, though you already closed it.
* I'll add a new API, like, HashMap::emplace<F: FnOnce() -> V>(&self, key: K, constructor: F) -> Result<Accessor, (Accessor, K)>, thereby allowing the API not to evaluate the given closure when the key exists.
* For, HashMap::reserve(&self, capacity: usize), I'll have to think about the return type. I'm currently not sure if an RAII-style object is suitable for the purpose.

It will take few days to implement both of them as 'scc' is a sort of free time activity and I don't spend much time on it.

Apart from your feature requests, I'd like to emphasize that the data structure is neither lock-free nor non-blocking. It achieves performance scalability by having fine granular locks installed in each hash table bucket (internally it is called a Cell, accommodating 32 entries) rather than a coarse lock managing an entire hash table or a shard. If you wish to try a true lock-free concurrent hash table, you should try https://crates.io/crates/evmap. What differentiates scc::HashMap from others like DashMap or Chashmap is, the total number of locks increases as the hash table grows whereas typical concurrent hash maps have a fixed number of locks.

**Comment by orenbenkiki** [comment]
Quick response!

Yes, a dedicated method would be more efficient.

And yes, I misspoke, it isn't lock free, of course. But it should scale better for my case (I hope) - millions of entries with several dozen threads doing insertions (but mostly doing lookups).

As for reserve - why should it have a return value at all?

**Comment by wvwwvwwv** [comment]
My experience with a database lock table with a conventional ‘reserve’ API semantics was very bad with a type of workload that frequently inserts and removes a large number of lock entries. For instance,
- Transaction 1 reserves 1M, the load factor immediately becomes ~0%.
- Transaction 2 removes entries from the lock table, immediately triggers automatic shrinking.
- Transaction 2 renders Transaction 1’s calling reserve(1M) futile.

As a solution to the problem, I resorted to using a type of ‘ReserveScope’ that prevents the lock table from shrinking under a certain level as long as the scope is valid.
- Transaction 1 reserves 1M, instantiating a ReserveScope.
- Transaction 2 removes entries, but the lock table does not shrink as Transaction 1 is holding a ReserveScope.

I’m now thinking of a reserve API returning a type of RAII-style object to keep the reservation valid for a desired period of time, but I’m not fully sure if this non-conventional semantics is suitable for a generic hash table (it is not a database lock table...).

**Comment by orenbenkiki** [comment]
Interesting scenario - in my case, I never delete entries so the issue doens't arise, but I understand the concern for a more general case.

Question though, don't you have the same problem with the initial size? Suppose I created a table with an initial size of 1M, added 10 entries, then deleted one - wouldn't this trigger a shrink?

Isn't the solution here that the table never shrinks below the original specified size?

In that case, I'd say there's an implicit (which should be made explicit) concept of "minimal capacity", which is initialized by the size parameter of the constructor. In this view, `reserve` increases the minimal capacity, and there should be `unreserve` which reduces it (or just give an `isize` parameter to reserve). Having a `minimal_capacity` query function also makes sense.

The table will never reduce the underlying storage size below the minimal capacity regardless of how low the load factor is. Calling `shrink` will only trim off excess capacity above the minimal value (again, regardless of how the load factor becomes). It would make sense to have `shrink_and_unreserve` which would shrink the table's storage to the bare minimum (maximal practical load factor, I doubt 100% is possible), reducing the minimal capacity as a result, so that no storage is "wasted" (to be used when one expects that there would be no additional inserts, or at least that they would be very rare).

In this approach there's no closure involved in all these methods (un/reserve, shrink/_and_unreserve), just the normal success/fail return value.

**Comment by wvwwvwwv** [comment]
The initial capacity is the minimum capacity of a hash table, hence the table won't be shrunk in that case (create 1M size -> insert -> delete).

Your idea - `reserve`, `unreserve`, and `shrink_and_unreserve` - looks great, and they can easily be implemented. Actually, I tried something similar at work when I dealt with the problem that I mentioned in my previous comment. It normally worked incredibly fine with most of the cases, but there was a tricky corner case that lead me to implement such a scoped object.

The semantics of the first version of 'reserve' was similar to that of std::vector.
* Transaction 1 reserves 1M: capacity becomes 1M.
* Transaction 2 reserves 1M: capacity stays the same.
and, the problem is obvious: half of the workload cannot benefit from the reservation.

The semantics of of the second version started to diverge from conventions.
* Initial state of the lock table: capacity = 1M, load factor = 0.6.
* Transaction 1 reserves 1M: capacity becomes 2M (0.6M + 1M < 2M), marks that 1M reserved.
* Transaction 2 reserves 1M: capacity becomes 4M (0.6M + 1M + 1M < 4M), marks that total 2M reserved.
* Transaction 2 is rolled back without using the reserved space.
and, the problem here is, the unused space is reclaimed way too late. That is the reason why I implemented ReserveScope that automatically `unreserves` the reserved space.

The final version is,
* Initial state of the lock table: capacity = 1M, load factor = 0.6.
* Transaction 1 reserves 1M: capacity becomes 2M (0.6M + 1M < 2M), marks that 1M are reserved.
* Transaction 2 reserves 1M: capacity becomes 4M (0.6M + 1M + 1M < 4M), marks that totally 2M are reserved.
* Transaction 2 is rolled back without using the reserved space.
* When the ReserveScope Transaction2 owns is destroyed, it tries to perform `shrink_to_fit` after `unreserve` the 1M space.

I have dealt with various database related issues for the past ten years at work, and I've come to believe that, the less the APIs and configurable parameters, the more stable the whole system becomes (and, more freedom, more pain). This is the reason why I did not simply implement `reserve`, `unreserve`, `shrink_to_fit`, or something similar, instead trying to devise a single, simple API that would be able to incorporate all the semantics that you mentioned, dealing with the corner cases above as well.
